### ISSUE TITLE
Crashing after getting to 100%

### ISSUE THREAD

**Issue by peva3** [Girish-Raguvir/PokemonGo-RedStreak#1]
```
Completed: 100.0%
---- Capturing Pokemon -----
Traceback (most recent call last):
  File "main.py", line 735, in <module>
    main()
  File "main.py", line 723, in main
    encounter_and_capture(pokemon)
  File "main.py", line 682, in encounter_and_capture
    cap_status = resp['responses']['CATCH_POKEMON']['status']
KeyError: 'status'
```

That's what I get when the searching gets to 100%, the first time I ran the script it completed successfully and caught a few pokemon, but when it got to 100% the next time it crashed. Any idea what's happening?

**Comment by girishjeyakumar** [comment]
Fixed in the lastest commit.Thanks for pointing it out.
