### ISSUE TITLE
Error when capturing pokemon

### ISSUE THREAD

**Issue by peva3** [Girish-Raguvir/PokemonGo-RedStreak#3]
```
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "main.py", line 725, in main
    encounter_and_capture(pokemon)
  File "main.py", line 660, in encounter_and_capture
    for x in resp['responses']['GET_MAP_OBJECTS']['map_cells']:
KeyError: 'GET_MAP_OBJECTS'

```

This happened after removing the stale pokemon from the list but before starting with the next round of searching.

**Comment by girishjeyakumar** [comment]
Fixed in the lastest commit.Thanks for pointing it out.
